### PR TITLE
Sanitise filenames in UploadAction

### LINKED ISSUE #272: Sanitise filenames in UploadAction
**Describe the bug**
Filenames containing `+` characters break the Kirby Panel when uploaded via the UploadAction.

**To Reproduce**
1. Create a form with the UploadAction
2. Upload a file named e.g. `test+file.jpg`
3. Open the page with the new file in the Panel
4. File can not be accessed, not even its dropdown

**Expected behaviour**
Filenames should be sanitised (like Kirby does for uploads in the Panel) using `F::safeName()` to prevent special characters from causing issues.

**Additional context**
The issue occurs in [UploadAction.php line 72](https://github.com/mzur/kirby-uniform/blob/master/src/Actions/UploadAction.php#L72) where `$name = $file['name']` uses the raw filename.

### PR DESCRIPTION
**Pull request by medienbaecker**
Fixes filenames with special characters (like `+`) that break the Panel by using Kirby's `F::safeName()` method, consistent with how Kirby handles uploads in the Panel itself.

Closes https://github.com/mzur/kirby-uniform/issues/272.

### CODE REVIEW

**Review by mzur — COMMENTED** [review]
Thanks! Could you please also add a test case for this? [Here](https://github.com/mzur/kirby-uniform/blob/bb8e634357024d2281d4c553c50664764822d4c6/tests/Actions/UploadActionTest.php#L104-L119) is an example.

File: tests/Actions/UploadActionTest.php [hunk 1]
```diff
@@ -99,6 +103,26 @@ public function testTargetFileIsFileWithPrefix()
...
+        ]);
+        $action = new UploadActionStub($this->form, ['fields' => [
+            'testfield' => ['target' => $path, 'prefix' => false],
+        ]]);
+
+        $action->perform();
+        $this->assertStringEndsWith('test-file.txt', $action->target);
+
+        @unlink("{$path}/test-file.txt");
+        @rmdir($path);
```
Comment (mzur) [inline tests/Actions/UploadActionTest.php:123]:
```suggestion
        try {
            $action->perform();
        } finally {
            @unlink("{$path}/test-file.txt");
            @rmdir($path);
        }
        
        $this->assertStringEndsWith('test-file.txt', $action->target);
```

**Review by mzur — COMMENTED** [review]
Thanks!
